# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:
    name: Build and compile project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install  
    - run: npm install
    - name: build
    - run: npm run build
      env:
        CI: true
